<h1>Справочник техники</h1>

<?php
$form->setAttribute('class', 'form-inline form-filter');
$form->prepare();
$form->setAttribute('action', $this->url('tech'));
?>
<?= $this->form()->openTag($form); ?>
<?php foreach ($form as $element) : ?>
    <?= $this->formElement($element); ?>&nbsp;
<?php endforeach; ?>
<?= $this->form()->closeTag(); ?>

<a href="<?= $this->url('tech', ['action' => 'add']); ?>" class="btn btn-default">Добавить</a>

<table class="table table-striped table-bordered main-table">
    <thead>
        <tr>
            <th>Наименование</th>
            <th>Подразделение</th>
            <th>Передвижная</th>
            <th>В архиве</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($rows as $line) :?>
            <tr>
                <td><?= $line->getName(); ?></td>
                <td><?= $line->getDepartment()->getName(); ?></td>
                <td>
                    <?php if ($line->isMovable()) :?>
                        Да
                    <?php else :?>
                        Нет
                    <?php endif;?>
                </td>
                <td>
                    <?php if ($line->isArchived()) :?>
                        Да
                    <?php else :?>
                        Нет
                    <?php endif;?>
                </td>
                <td class="action">
                    <a href="<?= $this->url('tech', ['action' => 'edit','id' => $line->getId()]); ?>">
                        <img src='/images/edit.png' alt='Редактировать'>
                    </a>
                    <?php if ($permissions['delete']) : ?>
                    <a class="confirm" href="<?= $this->url('tech', ['action' => 'delete','id' => $line->getId()]); ?>">
                        <img src='/images/del.png' alt='Удалить'>
                    </a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
