<h1>Пользование</h1>
<script>
    $(document).ready(function(){
        $('#startdate').datepicker();
        $('#enddate').datepicker();
    });
</script>
<?php
$form->setAttribute('class', 'form-inline form-filter');
$form->setAttribute('style', 'width:800px;display:block;margin:30px auto;');
$form->setAttribute('action', $this->url('containerRental'));
$form->prepare();
?>

<?= $this->form()->openTag($form); ?>
<?php foreach ($form as $element) : ?>
    <?= $this->formElement($element); ?> &nbsp;
<?php endforeach; ?>
<?= $this->form()->closeTag(); ?>

<h3>Остатки</h3>

<table class="table table-bordered main-table">
    <thead>
        <tr>
            <th>Компания</th>
            <th>Дебет</th>
            <th>Кредит</th>
            <th>Вагоны</th>
            <th>Сальдо(нам должны)</th>
        </tr>
    </thead>
    <?php foreach ($total as $row) :?>
        <tr>
            <td><?= $row['name']; ?></td>
            <td class="num"><?= $this->currencyFormat($row['debit'], 'RUR', null, 'ru_RU'); ?></td>
            <td class="num"><?= $this->currencyFormat($row['credit'], 'RUR', null, 'ru_RU'); ?></td>
            <td class="num"><?= $row['count']; ?></td>
            <td class="num"><?= $this->currencyFormat($row['balance'], 'RUR', null, 'ru_RU'); ?></td>
        </tr>
    <?php endforeach;?>
</table>

<h3>Расходы</h3>

<table class="table table-striped table-bordered main-table">
    <thead>
    <tr>
        <th>Дата акта</th>
        <th>Дата отгрузки</th>
        <th>Контейнер</th>
        <th>Собственник</th>
        <th>Цена</th>
        <th></th>
    </tr>
    </thead>
    <?php foreach ($containers as $container) :?>
        <tr>
            <td>
                <?= $container['extraOwner']['dateFormalString']; ?>
            </td>
            <td><?= $container['date'] ?></td>
            <td><?= $container['name'] ?></td>
            <td><?= $container['extraOwner']['ownerName'] ?></td>
            <td class="num">
                <?php if ($container['extraOwner']['isPaid']) : ?>
                    <span class="glyphicon glyphicon-ok text-success" aria-hidden="true"> </span>
                <?php endif; ?>
                <?= $this->currencyFormat($container['extraOwner']['ownerCost'], 'RUR', null, 'ru_RU'); ?>
            </td>
            <td>
                <?php if ($this->hasAccess(Modules\Controller\ContainerRentalController::class, 'edit')) : ?>
                    <a href="<?= $this->url('containerRental', ['action' => 'edit','id' => $container['id']]); ?>"><img src='/images/edit.png' alt='Редактировать'></a>
                <?php endif;?>
            </td>
        </tr>
    <?php endforeach;?>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td class="total num"><?= $this->currencyFormat($exp_sum, 'RUR', null, 'ru_RU'); ?></td>
        <td></td>
    </tr>
</table>
