<?php

use Phinx\Seed\AbstractSeed;

class MetalSeeder extends AbstractSeed
{
    protected $table = 'metal';

    /**
     * @var array Заполняемые данные
     */
    protected $data = [
        8 => ['id' => 8,
            'name' => 'Медь микс',
            'def' => 0,
            'group_id' => 6
        ],
        9 => ['id' => 9,
            'name' => 'Латунь',
            'def' => 0,
            'group_id' => 8],
        10 => ['id' => 10,
            'name' => 'Радиатор латунный',
            'def' => 0,
            'group_id' => 8],
        11 => ['id' => 11,
            'name' => 'Бронза кусковая',
            'def' => 0,
            'group_id' => 8],
        12 => ['id' => 12,
            'name' => 'Радиатор медный',
            'def' => 0,
            'group_id' => 6],
        14 => ['id' => 14,
            'name' => 'Алюминий хлам',
            'def' => 0,
            'group_id' => 7],
        15 => ['id' => 15,
            'name' => 'Нержавейка',
            'def' => 0,
            'group_id' => 9],
        16 => ['id' => 16,
            'name' => '3А',
            'def' => 1,
            'group_id' => 5],
        17 => ['id' => 17,
            'name' => '12А',
            'def' => 0,
            'group_id' => 5],
        18 => ['id' => 18,
            'name' => '5А',
            'def' => 0,
            'group_id' => 5],
        19 => ['id' => 19,
            'name' => 'Алюминий моторный',
            'def' => 0,
            'group_id' => 7],
        20 => ['id' => 20,
            'name' => 'Алюминий электротех',
            'def' => 0,
            'group_id' => 7],
        21 => ['id' => 21,
            'name' => 'Алюминий пищевой',
            'def' => 0,
            'group_id' => 7],
        22 => ['id' => 22,
            'name' => 'АКБ ПП',
            'def' => 0,
            'group_id' => 10],
        23 => ['id' => 23,
            'name' => 'Свинец кабельный',
            'def' => 0,
            'group_id' => 11],
        24 => ['id' => 24,
            'name' => 'Нержавейка н/г',
            'def' => 0,
            'group_id' => 9],
        25 => ['id' => 25,
            'name' => 'Стружка бронза',
            'def' => 0,
            'group_id' => 8],
        26 => ['id' => 26,
            'name' => 'Стружка латунь',
            'def' => 0,
            'group_id' => 8],
        27 => ['id' => 27,
            'name' => 'Олово',
            'def' => 0,
            'group_id' => 16],
        28 => ['id' => 28,
            'name' => 'Никель 100%',
            'def' => 0,
            'group_id' => 9],
        29 => ['id' => 29,
            'name' => 'Медь 1 группа(блестяшка)',
            'def' => 0,
            'group_id' => 6],
        30 => ['id' => 30,
            'name' => 'Медь 2 группа(кусок)',
            'def' => 0,
            'group_id' => 6],
        31 => ['id' => 31,
            'name' => 'Стружка медная',
            'def' => 0,
            'group_id' => 6],
        32 => ['id' => 32,
            'name' => 'Шина ад',
            'def' => 0,
            'group_id' => 7],
        33 => ['id' => 33,
            'name' => 'Медь 3 группа(шинка)',
            'def' => 0,
            'group_id' => 6],
        34 => ['id' => 34,
            'name' => 'Медь фосфористая',
            'def' => 0,
            'group_id' => 6],
        35 => ['id' => 35,
            'name' => 'Бронза 70-80',
            'def' => 0,
            'group_id' => 8],
        36 => ['id' => 36,
            'name' => 'Титан',
            'def' => 0,
            'group_id' => 9],
        37 => ['id' => 37,
            'name' => 'Банка',
            'def' => 0,
            'group_id' => 7],
        38 => ['id' => 38,
            'name' => 'Свинец микс',
            'def' => 0,
            'group_id' => 11],
        39 => ['id' => 39,
            'name' => 'Монель',
            'def' => 0,
            'group_id' => 9],
        40 => ['id' => 40,
            'name' => 'Нихром 80%',
            'def' => 0,
            'group_id' => 9],
        41 => ['id' => 41,
            'name' => 'Бабит 83%',
            'def' => 0,
            'group_id' => 19],
        42 => ['id' => 42,
            'name' => 'Цам',
            'def' => 0,
            'group_id' => 20],
        43 => ['id' => 43,
            'name' => 'Бабит 16%',
            'def' => 0,
            'group_id' => 19],
        44 => ['id' => 44,
            'name' => 'Цинк',
            'def' => 0,
            'group_id' => 14],
        45 => ['id' => 45,
            'name' => 'Лом латунных гильз 70-80',
            'def' => 0,
            'group_id' => 8],
        46 => ['id' => 46,
            'name' => 'Медно-никелевая трубка',
            'def' => 0,
            'group_id' => 8],
        47 => ['id' => 47,
            'name' => 'Лом латунной трубки',
            'def' => 0,
            'group_id' => 8],
        48 => ['id' => 48,
            'name' => 'Бронза 90% и более',
            'def' => 0,
            'group_id' => 8],
        49 => ['id' => 49,
            'name' => 'Ферованадий',
            'def' => 0,
            'group_id' => 21],
        50 => ['id' => 50,
            'name' => 'ВК ТК',
            'def' => 0,
            'group_id' => 22],
        51 => ['id' => 51,
            'name' => 'Стружка бронза 70-80',
            'def' => 0,
            'group_id' => 8],
        52 => ['id' => 52,
            'name' => 'Стружка бронза 80-90',
            'def' => 0,
            'group_id' => 8],
        53 => ['id' => 53,
            'name' => 'Бронза 80-90',
            'def' => 0,
            'group_id' => 8],
        54 => ['id' => 54,
            'name' => 'АКБ ГЕЛЬ',
            'def' => 0,
            'group_id' => 10],
        55 => ['id' => 55,
            'name' => 'АКБ ЭБ',
            'def' => 0,
            'group_id' => 10],
        56 => ['id' => 56,
            'name' => 'Магний',
            'def' => 0,
            'group_id' => 24],
        58 => ['id' => 58,
            'name' => 'Нихром 60%',
            'def' => 0,
            'group_id' => 9],
        59 => ['id' => 59,
            'name' => 'Никель 30%',
            'def' => 0,
            'group_id' => 9],
        60 => ['id' => 60,
            'name' => 'Никель 76%',
            'def' => 0,
            'group_id' => 9],
        61 => ['id' => 61,
            'name' => 'Электронный лом',
            'def' => 0,
            'group_id' => 25],
        62 => ['id' => 62,
            'name' => '25А',
            'def' => 0,
            'group_id' => 5],
        63 => ['id' => 63,
            'name' => '5АЭ',
            'def' => 0,
            'group_id' => 5],
        64 => ['id' => 64,
            'name' => '14А',
            'def' => 0,
            'group_id' => 5],
        65 => ['id' => 65,
            'name' => '5АЖД',
            'def' => 0,
            'group_id' => 5],
        66 => ['id' => 66,
            'name' => '16А',
            'def' => 0,
            'group_id' => 5],
        67 => ['id' => 67,
            'name' => '5АН',
            'def' => 0,
            'group_id' => 5],
        68 => ['id' => 68,
            'name' => '17А',
            'def' => 0,
            'group_id' => 5],
    ];

    /**
     * Добавляет тестовые данные для металлов
     *
     */
    public function run()
    {
        $metals = $this->query($this->getQueryString())->fetchAll();

        foreach ($metals as $metal) {
            if (isset($this->data[$metal['id']])) {
                unset($this->data[$metal['id']]);
            }
        }

        if (!empty($this->data)) {
            $table = $this->table($this->table);
            $table->insert(array_values($this->data))->save();
        }

    }

    /**
     * Возвращает строку запроса для поиска имеющихся металлов
     *
     * @return string
     */
    protected function getQueryString()
    {
        return "SELECT id FROM " . $this->table .
            " WHERE id IN ('" . implode("', '", array_keys($this->data)) . "')";
    }
}
