<?php
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>

<?= $this->form()->openTag($form); ?>

<?php $name = 'metal' ?>
    <div class="form-group <?= $this->formElementErrors($form->get($name)) ? 'error' : '' ?>">
        <label class="col-sm-3 control-label"><?= $form->get($name)->getLabel() ?></label>
        <div class="col-sm-4">
            <?= $this->formElement($form->get($name)); ?>
            <?php if ($this->formElementErrors($form->get($name))) : ?>
                <span class="help-inline"><?= $this->formElementErrors($form->get($name)); ?></span>
            <?php endif; ?>
        </div>
    </div>
<?php $name = 'comment' ?>
    <div class="form-group <?= $this->formElementErrors($form->get($name)) ? 'error' : '' ?>">
        <label class="col-sm-3 control-label"><?= $form->get($name)->getLabel(); ?></label>
        <div class="col-sm-4">
            <?= $this->formElement($form->get($name)); ?>
            <?php if ($this->formElementErrors($form->get($name))) : ?>
                <span class="help-inline"><?= $this->formElementErrors($form->get($name)); ?></span>
            <?php endif; ?>
        </div>
    </div>
<?php $name = 'weight' ?>
    <div class="weight form-group <?= $this->formElementErrors($form->get($name)) ? 'error' : '' ?>">
        <label class="col-sm-3 control-label"><?= $form->get($name)->getLabel(); ?></label>
        <div class="col-sm-4">
            <?= $this->formElement($form->get($name)); ?>
            <?php if ($this->formElementErrors($form->get($name))) : ?>
                <span class="help-inline"><?= $this->formElementErrors($form->get($name)); ?></span>
            <?php endif; ?>
        </div>
    </div>
<?php $name = 'realWeight' ?>
    <div class="real_weight form-group <?= $this->formElementErrors($form->get($name)) ? 'error' : '' ?>">
        <label class="col-sm-3 control-label"><?= $form->get($name)->getLabel(); ?></label>
        <div class="col-sm-4">

            <?= $this->formElement($form->get($name));?>
            <?php if ($this->formElementErrors($form->get($name))) : ?>
                <span class="help-inline"><?= $this->formElementErrors($form->get($name)); ?></span>
            <?php endif; ?>
        </div>
    </div>
<?php $name = 'cost' ?>
    <div class="form-group <?= $this->formElementErrors($form->get($name)) ? 'error' : '' ?>">
        <label class="col-sm-3 control-label"><?= $form->get($name)->getLabel(); ?></label>
        <div class="col-sm-4">
            <?= $this->formElement($form->get($name)); ?>
            <?php if ($this->formElementErrors($form->get($name))) : ?>
                <span class="help-inline"><?= $this->formElementErrors($form->get($name)); ?></span>
            <?php endif; ?>
        </div>
    </div>
<?php $name = 'costDol' ?>
    <div class="form-group <?= $this->formElementErrors($form->get($name)) ? 'error' : '' ?>">
        <label class="col-sm-3 control-label"><?= $form->get($name)->getLabel(); ?></label>
        <div class="col-sm-4">
            <?= $this->formElement($form->get($name)); ?>
            <?php if ($this->formElementErrors($form->get($name))) : ?>
                <span class="help-inline"><?= $this->formElementErrors($form->get($name)); ?></span>
            <?php endif; ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-3"></div>
        <div class="col-sm-4">
            <?php if ($isFerrous) : ?>
                <?= $this->formElement($form->get('submit')->setValue('Добавить вагон')); ?>
                <div id="save" class="btn btn-default">Сохранить</div>
            <?php else : ?>
                <?= $this->formElement($form->get('submit')->setValue('Добавить')); ?>
                <div id="save" class="btn btn-default">Сохранить контейнер</div>
            <?php endif; ?>
        </div>
    </div>

<?= $this->form()->closeTag(); ?>
