
<h1>Инвентаризации</h1>
<script>
    $(function() {
        $('#startdate').datepicker();
        $('#enddate').datepicker();
    });
</script>
<?php
$form->setAttribute('class', 'form-inline form-filter');
$form->prepare();
$form->setAttribute('action', $this->url('spareInventory', $routParams));
?>
<?= $this->form()->openTag($form) ?>
<?php foreach ($form as $element) : ?>
    <?= $this->formElement($element) ?>&nbsp;
<?php endforeach; ?>
<?= $this->form()->closeTag() ?>

<div class="flashInfo"><?= $this->flashMessenger()->render(); ?></div>

<?php if (! empty($permissions['add'])) : ?>
    <p>
        <a href="<?= $this->url('spareInventory', array_merge(['action' => 'add'], $routParams))?>"
           class="btn btn-default">
            Добавить
        </a>
    </p>
<?php endif; ?>

    <table class="table table-striped table-bordered main-table">
        <thead>
        <tr>
            <th style="width: 33%;">Дата проведения</th>
            <th style="width: 33%;">Статуст</th>
            <th style="width: 33%;"> </th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($inventories as $inventory) : /**@var \Spare\Entity\Inventory $inventory*/?>
            <tr class="<?= $inventory->getStatus() ?>">
                <td><?= $inventory->getDate() ?></td>
                <td style="text-align: center;"> <span class="<?= $inventory->getStatus() ?>"> </span></td>
                <td style="text-align: center;">
                    <?php if (! empty($permissions['edit'])) : ?>
                        <a href="<?= $this->url('spareInventory', array_merge(
                            ['action' => 'edit', 'id' => $inventory->getId()],
                            $routParams
                        )); ?>">
                            <img src='/images/edit.png' alt='Редактировать'>
                        </a>
                    <?php endif; ?>
                    <?php
                    $isLastInventory = $lastInventory->getId() == $inventory->getId();
                    $hasAccessForDelete = ! empty($permissions['delete']) && $inventory->getDate() == date('Y-m-d');
                    if (($isAdmin || $hasAccessForDelete) && $isLastInventory) : ?>
                        <a class="confirm"
                           href="<?= $this->url('spareInventory', array_merge(
                               ['action' => 'delete', 'id' => $inventory->getId()],
                               $routParams
                           )); ?>">
                            <img src='/images/del.png' alt='Удалить'>
                        </a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
