<?php $this->headTitle('Ведомость расчетов с контрагентами :: '); ?>
<h1>Ведомость расчетов с контрагентами</h1>

<script>
    $(document).ready(function () {
        $('#startdate').datepicker();
        $('#enddate').datepicker();
    });
</script>

<?php
    $form->setAttribute('class', 'form-inline form-filter');
    $form->prepare();
    $form->setAttribute('action', $this->url('spareBalance'));
?>
<?= $this->form()->openTag($form); ?>
    <?php foreach ($form as $element) : ?>
        <?= $this->formElement($element); ?>&nbsp;
    <?php endforeach; ?>
<?= $this->form()->closeTag(); ?>

<table class="table table-striped table-bordered main-table">
    <thead>
    <tr>
        <th>Поставщик</th>
        <th>Заказано</th>
        <th>Оплачено</th>
        <th>Сальдо</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($balanceData as $item) :?>
        <tr>
            <td><?= $item['name']; ?></td>
            <td class="num"><?= $item['order_sum']; ?></td>
            <td class="num"><?= $item['expense_sum']; ?></td>
            <td class="num"><?= $item['balance']; ?></td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>
