<h1>Тарифы отгрузки</h1>

<a href="<?= $this->url('shipmentTariff', ['action' => 'add'])?>" class="btn btn-default">Добавить</a>

<table class="table table-striped table-bordered main-table">
    <thead>
        <tr>
            <th>Наименование</th>
            <th>Завод</th>
            <th>Дистанция</th>
            <th>Тип</th>
            <th>Оплата собственнику</th>
            <th>По умолчанию</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($rows as $line) :?>
            <tr>
                <td><?= $line->getName(); ?></td>
                <td><?= $line->getDestination(); ?></td>
                <td><?= $line->getDistance(); ?></td>
                <td>
                    <?php if ($line->getType() == 'black') :?>
                        Черный
                    <?php else : ?>
                        Цветной
                    <?php endif; ?>
                </td>
                <td><?= $line->getMoney(); ?></td>
                <td>
                    <?php if ($line->getDef()) :?>
                        Да
                    <?php else : ?>
                        Нет
                    <?php endif; ?>
                </td>
                <td class="action">
                    <a href="<?= $this->url('shipmentTariff', ['action' => 'edit','id' => $line->getId()]); ?>">
                        <img src='/images/edit.png' alt='Редактировать'>
                    </a>
                    <a class="confirm" href="<?= $this->url('shipmentTariff', ['action' => 'delete','id' => $line->getId()]); ?>">
                        <img src='/images/del.png' alt='Удалить'>
                    </a>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
