<h1>Водители</h1>

<?php if (! empty($errors)) : ?>
    <ul>
        <?php foreach ($errors as $error) : ?>
            <li class="validation-error-message"><?= $error ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

<div class="flashInfo"><?= $this->flashMessenger()->render(); ?></div>

<?php if (! empty($permissions['add'])) : ?>
    <a href="<?= $this->url('shipmentDocs/driver', ['action' => 'add']); ?>" class="btn btn-default">Добавить</a>
<?php endif; ?>

<table class="table table-striped table-bordered main-table">
    <thead>
    <tr>
        <th>ФИО</th>
        <th>Паспорт</th>
        <th>Водительское удостоверение</th>
        <th> </th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($data as $driver) : ?>
        <tr>
            <td><?= $driver['surname'] . ' ' . $driver['name'] . ' ' . $driver['patronymic'] ?></td>
            <td><?= $driver['passport_series'] . ' ' . $driver['passport_number'] . ' от ' . $driver['issued_by']?></td>
            <td><?= $driver['license'] ?></td>
            <td>
                <?php if (! empty($permissions['edit'])) : ?>
                    <a href="<?= $this->url('shipmentDocs/driver', ['action' => 'edit','id' => $driver['id']]); ?>">
                        <img src='/images/edit.png' alt='Редактировать'>
                    </a>
                <?php endif; ?>
                <?php if (! empty($permissions['delete'])) : ?>
                    <a class="confirm" href="<?= $this->url('shipmentDocs/driver', ['action' => 'delete','id' => $driver['id']]); ?>">
                        <img src='/images/del.png' alt='Удалить'>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
