<h1>Заявки</h1>
<script>
    $(function() {
        $('#startdate').datepicker();
        $('#enddate').datepicker();
        $(".s2").select2();
    });
</script>

<?php
$form->setAttribute('class', 'form-inline form-filter');
$form->prepare();
$form->setAttribute('action', $this->url('spare_planning'));
?>
<?= $this->form()->openTag($form) ?>
<?php foreach ($form as $element) : ?>
    <?= $this->formElement($element) ?>&nbsp;
<?php endforeach; ?>
<?= $this->form()->closeTag() ?>

<div class="flashInfo"><?= $this->flashMessenger()->render(); ?></div>
<?php if (! empty($permissions['add'])) : ?>
    <p>
        <a href="<?=$this->url('spare_planning', ['action' => 'add'])?>" class="btn btn-default">Добавить</a>
    </p>
<?php endif; ?>

<?php foreach ($plannings as $planning) : ?>
    <a name="planning<?=$planning->getId() ?>"></a>
    <span style="font-weight: bold;"><?= $planning->getDate() ?></span>  №<?= $planning->getId()?>
    <span style="font-weight: bold;">Статус:</span>
    <span style="color: <?= $planning->getStatus()->getColorStatus(); ?>">
        <?= $planning->getStatus()->getTitle() ?>
    </span>
    <?php if ($planning->getEmployee()) : ?>
        <span><?=$planning->getEmployee()->getName(); ?></span>
    <?php endif; ?>
    <?php if ($planning->getVehicle()) : ?>
        <span><?=$planning->getVehicle()->getName(); ?></span>
    <?php endif; ?>
    <?php if (! empty($permissions['edit'])) : ?>
        <a href="<?= $this->url('spare_planning', ['action' => 'edit', 'id' => $planning->getId()]); ?>">
            <img src='/images/edit.png' alt='Редактировать'>
        </a>
    <?php endif; ?>
    <?php if (! empty($permissions['delete'])) : ?>
        <a class="confirm"
           href="<?= $this->url('spare_planning', ['action' => 'delete', 'id' => $planning->getId()]); ?>">
            <img src='/images/del.png' alt='Удалить'>
        </a>
    <?php endif; ?>
    <?php if (! empty($permissions['inwork'])) : ?>
        <a class="confirm" href="<?= $this->url('spare_planning', ['action' => 'in-work', 'id' => $planning->getId()]); ?>">
            <img src='/images/inwork.png' alt='Принять в работу'>
        </a>
    <?php endif; ?>

    <table class="table table-striped table-bordered main-table">
        <thead>
        <tr>
            <th style="width: 25%;">Запчасть</th>
            <th style="width: 25%;">Количество в плане</th>
            <th style="width: 25%;">Количество в заказе</th>
            <th style="width: 25%;">Остаток</th>
            <th>Удалить</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($planning->getItems() as $item) : ?>
            <tr>
                <td><?= $item->getSpare()->getName() ?></td>
                <td style="text-align: center;"><?= $item->getQuantity() ?> <?= $item->getSpare()->getUnits() ?></td>
                <td style="text-align: center;"><?= $item->getOrdered() ?> <?= $item->getSpare()->getUnits() ?></td>
                <td style="text-align: center;"><?= $item->getQuantity() - $item->getOrdered() ?> <?= $item->getSpare()->getUnits() ?></td>
                <td class="action">
                    <?php if ($item->isDeletable()) : ?>
                        <a class="confirm" href="<?= $this->url('spare_planning', ['action' => 'delete-item','id' => $item->getId()]); ?>">
                            <img src='/images/del.png' alt='Удалить'>
                        </a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <?php if (! empty($planning->getComment())) : ?>
        <div class="spareComment">
            <p class="info">Комментарий: <em style="font-weight: 300"><?= $planning->getComment() ?></em></p>
        </div>
    <?php endif; ?>
    <hr class="break10">
<?php endforeach; ?>
