<h1>Передача денег из подразделения в подразделение</h1>

<script>
    $(document).ready(function(){
        $('#startdate').datepicker();
        $('#enddate').datepicker();
    });
</script>

<?php
$form->setAttribute('class', 'form-inline form-filter');
$form->prepare();
$form->setAttribute('action', $this->url('storageCashTransfer', ['department' => $dep]));
?>
<?= $this->form()->openTag($form); ?>
<?php foreach ($form as $element) : ?>
    <?= $this->formElement($element); ?> &nbsp;
<?php endforeach; ?>
<?= $this->form()->closeTag(); ?>

<?php if ($this->hasAccess(Storage\Controller\CashTransferController::class, 'add')) : ?>
    <a href="<?= $this->url('storageCashTransfer', ['action' => 'add','department' => $dep])?>" class="btn btn-default">Добавить</a>
<?php endif;?>


<table class="table table-striped table-bordered main-table">
    <thead>
    <tr>
        <th>Дата</th>
        <th>Отправитель</th>
        <th>Получатель</th>
        <th>Сумма</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($rows as $line) :?>
        <tr>
            <td><?= $line->getDate()?></td>
            <td><?= $line->getSource()->getName(); ?></td>
            <td><?= $line->getDest()->getName(); ?></td>
            <td class="num"><?= $this->currencyFormat($line->getMoney(), 'RUR', null, 'ru_RU'); ?></td>
            <td class="action">
                <?php if ($this->hasAccess(Storage\Controller\CashTransferController::class, 'delete')) :?>
                    <a href="<?= $this->url('storageCashTransfer', ['action' => 'edit','id' => $line->getId(),'department' => $dep]); ?>">
                        <img src='/images/edit.png' alt='Редактировать'>
                    </a>
                <?php endif;?>
                <?php if ($this->hasAccess(Storage\Controller\CashTransferController::class, 'delete')) :?>
                    <a class="confirm" href="<?= $this->url('storageCashTransfer', ['action' => 'delete','id' => $line->getId(),'department' => $dep]); ?>">
                        <img src='/images/del.png' alt='Удалить'>
                    </a>
                <?php endif;?>
            </td>
        </tr>
    <?php endforeach;?>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td class="total num"><?= $this->currencyFormat($money, 'RUR', null, 'ru_RU'); ?></td>
        <td></td>
    </tr>
    </tbody>
</table>
