<h1>Заказы</h1>
<script>
    $(function() {
        $('#startdate').datepicker();
        $('#enddate').datepicker();
        $(".s2").select2();
        $("[name='seller']").select2();
    });
</script>
<?php
$form->setAttribute('class', 'form-inline form-filter');
$form->prepare();
$form->setAttribute('action', $this->url('spareOrder'));
?>
<?= $this->form()->openTag($form) ?>
<?php foreach ($form as $element) : ?>
    <?= $this->formElement($element) ?>&nbsp;
<?php endforeach; ?>
<?= $this->form()->closeTag() ?>

<div class="flashInfo"><?= $this->flashMessenger()->render(); ?></div>

<?php if (! empty($permissions['add'])) : ?>
    <p>
        <a style="margin-bottom: 15px;" href="<?= $this->url('spareOrder', ['action' => 'add'])?>" class="btn btn-default">
            Добавить
        </a>
        <div style="text-align: right;">Сумма по выбранным заказам: <strong><?= $this->currencyFormat($totalAmount, 'RUR', null, 'ru_RU')?></strong></div>
    </p>
<?php endif; ?>
<?php foreach ($orders as $order) : ?>
    <a name="order<?=$order->getId() ?>"></a>
    <span style="font-weight: bold;"><?= $order->getDate() ?></span> №<?= $order->getId()?> <?= $order->getDocument() ?>
    <span style="font-weight: bold;">Поставщик:</span> <?= $order->getSeller()->getName() ?>
    <span style="color: <?= $order->getStatus()->getColorStatus(); ?>">
        <?= $order->getStatus()->getTitle() ?>
    </span>

    <span style="font-weight: bold;"> Статус оплаты: </span>
    <?= $order->getPaymentStatus()->getTitle() ?>

    <?php if (! empty($permissions['edit'])) : ?>
        <a href="<?= $this->url('spareOrder', ['action' => 'edit', 'id' => $order->getId()]); ?>">
            <img src='/images/edit.png' alt='Редактировать'>
        </a>
    <?php endif; ?>

    <?php if ($permissions['delete']) : ?>
        <a class="confirm"
           href="<?= $this->url('spareOrder', ['action' => 'delete', 'id' => $order->getId()]); ?>">
            <img src='/images/del.png' alt='Удалить'>
        </a>
    <?php endif; ?>
    <table class="table table-striped table-bordered main-table">
        <thead>
        <tr>
            <th style="width: 16%;">Запчасть</th>
            <th>Заявка</th>
            <th style="width: 16%;">Заказанно</th>
            <th style="width: 16%;">Принято</th>
            <th style="width: 16%;">Количество единиц в упаковке</th>
            <th style="width: 16%;">Цена<br>(за упаковку)</th>
            <th style="width: 16%;">Сумма</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($order->getItems() as $orderItem) : ?>
            <tr>
                <td><?= $orderItem->getSpare()->getName() ?></td>
                <td style="text-align: center;">
                    <a href="<?=$this->url('spare_planning') ?>#planning<?= $orderItem->getPlanningItem()->getPlanning()->getId() ?>">
                        <?= $orderItem->getPlanningItem()->getPlanning()->getId() ?>
                    </a>
                </td>
                <td style="text-align: center;"><?= $orderItem->getQuantity() ?> шт.</td>
                <td style="text-align: center;"><?= $orderItem->getReceipted(false) ?></td>
                <td style="text-align: center;"><?= $orderItem->getSubQuantity() ?: '-' ?>  <?= $orderItem->getSubQuantity() ? $orderItem->getSpare()->getUnits() : '' ?></td>
                <td class="num"><?= $this->currencyFormat($orderItem->getPrice(), 'RUR', null, 'ru_RU'); ?></td>
                <td class="num"><?= $this->currencyFormat($orderItem->getOrderItemsPrice(), 'RUR', null, 'ru_RU'); ?></td>
            </tr>
        <?php endforeach; ?>
        <tr>
            <td> </td>
            <td> </td>
            <td> </td>
            <td> </td>
            <td> </td>
            <td> </td>
            <td class="num total"><?= $this->currencyFormat($order->getPrice(), 'RUR', null, 'ru_RU'); ?></td>
        </tr>
        </tbody>
    </table>
<?php endforeach; ?>
