<?php
$form = $this->form;
$form->setAttribute('action', $this->url('factoring_assignment_debt', ['action' => $this->currentRoute()->getAction(), 'id' => $id ?? null]));
$form->setAttribute('class', 'form-horizontal form-add');
?>
<?= $form->prepare() ?>
<?php if ($this->message) : ?>
    <p class="alert-danger"><?= $this->message; ?></p>
<?php endif; ?>

<?= $this->form()->openTag($form); ?>
<?php foreach ($form as $element) : ?>
    <div class="form-group <?= $this->formElementErrors($element) ? 'error' : '' ?>">
        <label class="col-sm-3 control-label"><?= $element->getLabel() ?></label>
        <div class="col-sm-4">
            <?= $this->formElement($element); ?>
            <?php if ($this->formElementErrors($element)) : ?>
                <span class="help-inline"><?= $this->formElementErrors($element) ?></span>
            <?php endif; ?>
        </div>
    </div>
<?php endforeach; ?>

<?= $this->form()->closeTag(); ?>
