<h1>Авансы контрагентам</h1>

<a href="<?= $this->url('customer_debt', ['action' => 'add']); ?>" class="btn btn-default">Добавить</a>

<div style="margin-top:20px;">

    <table class="table table-striped table-bordered main-table">
        <thead>
        <tr>
            <th>Дата</th>
            <th>Контрагент</th>
            <th>Сумма</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($rows as $row) : ?>
            <tr>
                <td><?= $row->getDate(); ?></td>
                <td><?= $row->getCustomer()->getName(); ?></td>
                <td><?= $this->currencyFormat($row->getAmount(), 'RUR'); ?></td>
                <td class="action">
                    <a href="<?= $this->url('customer_debt', ['action' => 'edit', 'id' => $row->getId()]); ?>">
                        <img src='/images/edit.png' alt='Редактировать'>
                    </a>
                    <a class="confirm"
                       href="<?= $this->url('customer_debt', ['action' => 'delete', 'id' => $row->getId()]); ?>">
                        <img src='/images/del.png' alt='Удалить'>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

</div>
