<h1>Категории расходов</h1>

<a href="<?= $this->url('category', ['action' => 'add']); ?>" class="btn btn-default">Добавить</a>

<table class="table table-striped table-bordered main-table">
    <thead>
        <tr>
            <th>Наименование</th>
            <th>Группа</th>
            <th>По умолчанию</th>
            <th>В архиве</th>
            <th>Роли</th>
            <th style="width: 20px;"></th>
        </tr>
    </thead>
    <tbody>
        <?php if ($rows) : ?>
            <?php foreach ($rows as $line) :?>
                <tr>
                    <td><?= $line->getName(); ?></td>
                    <td><?= $line->getGroup()->getName(); ?></td>
                    <td>
                        <?php if ($line->isDefault()) :?>
                            Да
                        <?php else :?>
                            Нет
                        <?php endif;?>
                    </td>
                    <td>
                        <?php if ($line->isArchived()) :?>
                            Да
                        <?php else :?>
                            Нет
                        <?php endif;?>
                    </td>
                    <td>
                        <?php foreach ($line->getRoles() as $role) : ?>
                            <?= $role->getName(); ?>
                        <?php endforeach; ?>
                    </td>
                    <td class="action">
                        <a href="<?= $this->url('category', ['action' => 'edit','id' => $line->getId()]); ?>">
                            <img src='/images/edit.png' alt='Редактировать'>
                        </a>
                        <a class="confirm" href="<?= $this->url('category', ['action' => 'delete','id' => $line->getId()]); ?>">
                            <img src='/images/del.png' alt='Удалить'>
                        </a>
                    </td>
                </tr>
            <?php endforeach;?>
        <?php endif; ?>
    </tbody>
</table>
