<h1>Завершенные выезды техники</h1>

<script>
    $(document).ready(function () {
        $('#startdate').datepicker();
        $('#enddate').datepicker();
    });
</script>
<div class="filter">
    <?php
    $form->setAttribute('class', 'form-inline form-filter');
    $form->setAttribute('action', $this->url('completedVehicleTrips'));
    ?>
    <?= $this->form()->openTag($form); ?>
    <div class="items">
        <span><?= $this->formElement($form->get('startdate')); ?></span>
        <span><?= $this->formElement($form->get('enddate')); ?></span>
        <span><?= $this->formElement($form->get('customerText')); ?></span>
        <span><?= $this->formElement($form->get('vehicle')); ?></span>
        <span><?= $this->formElement($form->get('department')); ?></span>
        <br>
        <span><?= $this->formElement($form->get('weightFrom')); ?></span>
        <span><?= $this->formElement($form->get('weightTo')); ?></span>
        <span><?= $this->formElement($form->get('submit')); ?></span>
    </div>
    <?= $this->form()->closeTag(); ?>
</div>

<table class="table table-striped table-bordered main-table">
    <thead>
    <tr>
        <th>Дата</th>
        <th>Клиент</th>
        <th>Техника</th>
        <th>км в одну сторону</th>
        <th>Оплата</th>
        <th>Подразделение</th>
        <th>Номер накладной</th>
        <th>Масса</th>
        <th>Комментарий</th>
        <?php if ($permissions['edit'] || $permissions['delete']) : ?>
            <th></th>
        <?php endif; ?>
    </tr>
    </thead>
    <tbody>
    <?php
    $total = 0;
    $weight = 0;
    ?>
    <?php foreach ($data as $line) : ?>
        <tr>
            <td class="date"><?= $line->getDate(); ?></td>
            <td><?= $line->getCustomer(); ?></td>
            <td><?= $line->getVehicle()->getName(); ?></td>
            <td class="num"><?= $line->getDistance() ?></td>
            <td class="num"><?= $this->currencyFormat($line->getPayment(), 'RUR', null, 'ru_RU'); ?></td>
            <td><?= $line->getDepartment()->getName(); ?></td>
            <td><?= $line->getWaybill(); ?></td>
            <?php
            if (! empty($line->getRemoteSklad())) {
                $wmassa = $line->getRemoteSklad()->getMassa();
                if ($wmassa < 0) {
                    $wmassa = -$wmassa;
                }
                $weight += $wmassa;
            }
            ?>
            <td class="num">
                <?= ! empty($line->getRemoteSklad())
                    ? $this->numberFormat($wmassa, NumberFormatter::DECIMAL, NumberFormatter::TYPE_DEFAULT, "ru_RU")
                    : '0';
                ?>
                &nbsp;кг.
            </td>
            <td><?= $line->getComment(); ?></td>
            <?php if ($permissions['edit'] || $permissions['delete']) : ?>
                <td>
                    <?php if (($permissions['delete'] || $this->isNormalLimitMonth($line->getDate(), 2)) && $permissions['edit']) : ?>
                        <a href="<?= $this->url('completedVehicleTrips', ['action' => 'edit', 'id' => $line->getId()]); ?>">
                            <img src='/images/edit.png' alt='Редактировать'>
                        </a>
                    <?php endif; ?>
                    <?php if ($permissions['delete']) : ?>
                        <a class="confirm" href="<?= $this->url('completedVehicleTrips', ['action' => 'delete', 'id' => $line->getId()]); ?>">
                            <img src='/images/del.png' alt='Удалить'>
                        </a>
                    <?php endif; ?>
                </td>
            <?php endif; ?>
            <?php $total += $line->getPayment() ?>
        </tr>
    <?php endforeach; ?>
    <tr>
        <td></td>
        <td></td>
        <td><strong>Итого:</strong></td>
        <td></td>
        <td class="total num"><?= $this->currencyFormat($total, 'RUR', null, 'ru_RU') ?></td>
        <td></td>
        <td><strong>Общая масса</strong></td>
        <td class="total num"><?= $this->numberFormat($weight, NumberFormatter::DECIMAL, NumberFormatter::TYPE_DEFAULT, "ru_RU"); ?>
            &nbsp;кг.
        </td>
        <td></td>
        <?php if ($permissions['edit'] || $permissions['delete']) : ?>
            <td></td>
        <?php endif; ?>
    </tr>
    </tbody>
</table>
