<h1>Справочник сотрудников</h1>

<a href="<?= $this->url('employee', ['action' => 'add']) ?>" class="btn btn-default">Добавить</a>

<table class="table table-striped table-bordered main-table">
    <thead>
    <tr>
        <th>ФИО сотрудника</th>
        <th>Номер водительского удостоверения</th>
        <th><?= \Core\Utils\Options::OPTIONS_DRIVER ?></th>
        <th><?= \Core\Utils\Options::OPTIONS_SPARE ?></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($rows as $line) : ?>
        <tr>
            <td><?= $line->getName(); ?></td>
            <td><?= $line->getLicense(); ?></td>
            <td style="text-align: center">
                <?php if ($line->isDriver()) :?>
                    <strong style="color: red">&#10004;</strong>
                <?php else :?>
                    &#10008;
                <?php endif;?>
            </td>
            <td style="text-align: center">
                <?php if ($line->isSpare()) :?>
                    <strong style="color: red">&#10004;</strong>
                <?php else :?>
                    &#10008;
                <?php endif;?>
            </td>
            <td class="action">
                <a href="<?= $this->url('employee', ['action' => 'edit', 'id' => $line->getId()]); ?>">
                    <img src='/images/edit.png' alt='Редактировать'>
                </a>
                <a class="confirm"
                   href="<?= $this->url('employee', ['action' => 'delete', 'id' => $line->getId()]); ?>">
                    <img src='/images/del.png' alt='Удалить'>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
