<h1>Группы металлов</h1>

<a href="<?= $this->url('metalGroup', ['action' => 'add'])?>" class="btn btn-default">Добавить</a>

<table class="table table-striped table-bordered main-table">
    <thead>
        <tr>
            <th>Наименование</th>
            <th>Тип</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($rows as $line) :?>
            <tr>
                <td><?= $line->getName(); ?></td>
                <td>
                    <?php if ($line->getFerrous()) :?>
                        Черный
                    <?php else : ?>
                        Цветной
                    <?php endif;?>
                </td>
                <td class="action">
                    <a href="<?= $this->url('metalGroup', ['action' => 'edit','id' => $line->getId()]); ?>">
                        <img src='/images/edit.png' alt='Редактировать'>
                    </a>
                    <a class="confirm" href="<?= $this->url('metalGroup', ['action' => 'delete','id' => $line->getId()]); ?>">
                        <img src='/images/del.png' alt='Удалить'>
                    </a>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
