<h1>Наличная оплата</h1>
<?php $this->initScript('spare/payment'); ?>

<div id="app">
    <spare-payment-form-panel
        :save-bind-url="'<?=$saveBindUrl?>'"
        :remove-bind-url="'<?=$removeBindUrl?>'"
        :get-expenses-uri="'<?=$getExpensesUri?>'"
        :order-url="'<?=$orderUrl?>'"
        :search-data='<?=$searchData?>'
        :expenses-list='<?=$expensesList?>'
        :orders-list='<?=$orders?>'
        :sellers='<?=$sellers?>'

    ></spare-payment-form-panel>
</div>

