<?php $this->headTitle('Факторинг - Реализация :: '); ?>
<h1>Факторинг - Реализация</h1>

<script>
    $(function() {
        $('#startdate').datepicker();
        $('#enddate').datepicker();
    });
</script>

<?php
$this->form->setAttribute('class', 'form-inline form-filter');
$this->form->setAttribute('action', $this->url('factoring_sales'));
?>

<?= $this->form()->openTag($this->form) ?>
    <?php foreach ($this->form as $element) : ?>
        <?= $this->formElement($element) ?>&nbsp;
    <?php endforeach; ?>
<?= $this->form()->closeTag() ?>

<table class="table table-striped table-bordered main-table">
    <thead>
    <tr>
        <th>Дата</th>
        <th>Контрагент</th>
        <th>Сумма</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($data['items'] as $item) : ?>
        <tr>
            <td class="date"><?= $item['date']; ?></td>
            <td><?= $item['trader']['name']; ?></td>
            <td class="num"><?= $this->currencyFormat($item['sum'], 'RUR', null, 'ru_RU'); ?></td>
        </tr>
    <?php endforeach; ?>
    <tr>
        <td></td>
        <td></td>
        <td class="total num"><?= $this->currencyFormat($data['sum'], 'RUR', null, 'ru_RU'); ?></td>
    </tr>
    </tbody>
</table>

