<h1>Группы категорий</h1>

<a href="<?= $this->url('categoryGroup', ['action' => 'add']); ?>" class="btn btn-default">Добавить</a>

<table class="table table-striped table-bordered main-table">
    <thead>
        <tr>
            <th>Наименование</th>
            <th>Порядок</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($rows as $line) :?>
            <tr>
                <td><?= $line->getName(); ?></td>
                <td><?= $line->getSortOrder(); ?></td>
                <td class="action">
                    <a href="<?= $this->url('categoryGroup', ['action' => 'edit','id' => $line->getId()]); ?>">
                        <img src='/images/edit.png' alt='Редактировать'>
                    </a>
                    <a class="confirm" href="<?= $this->url('categoryGroup', ['action' => 'delete','id' => $line->getId()]); ?>">
                        <img src='/images/del.png' alt='Удалить'>
                    </a>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
