<h1>Справочник поставщиков(<?=count($rows) ?>)</h1>

<?php
    $form->setAttribute('class', 'form-inline form-filter');
    $form->prepare();
    $form->setAttribute('action', $this->url('customer'));
?>
<?= $this->form()->openTag($form); ?>
<?php foreach ($form as $element) : ?>
    <?= $this->formElement($element); ?> &nbsp;
<?php endforeach; ?>
<?= $this->form()->closeTag(); ?>

<a href="<?= $this->url('customer', ['action' => 'add'])?>" class="btn btn-default">Добавить</a>

<div style="margin-top:20px;">

    <table class="table table-striped table-bordered main-table">
        <thead>
            <tr>
                <th>Наименование</th>
                <th>ИНН</th>
                <th>По умолчанию</th>
                <th>Юр. лицо</th>
                <th>Архивный</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($rows as $row) : ?>
                <tr>
                    <td><?= $row->getName() ?></td>
                    <td><?= $row->getInn() ?></td>
                    <td class="text-center">
                        <?php if ($row->getDef()) : ?>
                            <span class="glyphicon glyphicon-ok text-success" aria-hidden="true"></span>
                        <?php else : ?>
                            <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                        <?php endif; ?>
                    </td>
                    <td class="text-center">
                        <?php if ($row->getLegal()) : ?>
                            <span class="glyphicon glyphicon-ok text-success" aria-hidden="true"></span>
                        <?php else : ?>
                            <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                        <?php endif; ?>
                    </td>
                    <td class="text-center">
                        <?php if ($row->isArchive()) : ?>
                            <span class="glyphicon glyphicon-ok text-success" aria-hidden="true"></span>
                        <?php else : ?>
                            <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                        <?php endif; ?>
                    </td>
                    <td class="action">
                        <a href="<?= $this->url('customer', ['action' => 'edit', 'id' => $row->getId() ]); ?>">
                            <img src='/images/edit.png' alt='Редактировать'>
                        </a>
                        <a class="confirm" href="<?= $this->url('customer', ['action' => 'delete', 'id' => $row->getId() ]); ?>">
                            <img src='/images/del.png' alt='Удалить'>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

</div>
