<h1>Справочник поставщиков</h1>

<script>
    $(function() {
        $("[name='seller']").select2();
    });
</script>

<?php
$form->setAttribute('class', 'form-inline form-filter');
$form->prepare();
$form->setAttribute('action', $this->url('spareSeller'));
?>

<?= $this->form()->openTag($form); ?>
<?php foreach ($form as $element) : ?>
    <?= $this->formElement($element); ?>&nbsp;
<?php endforeach; ?>
<?= $this->form()->closeTag(); ?>

<?php if ($this->permissions['add']) : ?>
    <a href="<?= $this->url('spareSeller', ['action' => 'add']) ?>" class="btn btn-default">Добавить</a>
<?php endif; ?>

<table class="table table-striped table-bordered main-table">
    <thead>
    <tr>
        <th>Поставщик</th>
        <th>Инн</th>
        <th>Контакты</th>
        <th>Комментарий</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->rows as $line) : ?>
        <tr>
            <td><?= $line->getName(); ?></td>
            <td><?= $line->getInn(); ?></td>
            <td><?= $line->getContacts(); ?></td>
            <td><?= $line->getComment(); ?></td>
            <td class="action">
                <?php if ($this->permissions['edit']) : ?>
                    <a href="<?= $this->url('spareSeller', ['action' => 'edit', 'id' => $line->getId()]); ?>">
                        <img src='/images/edit.png' alt='Редактировать'>
                    </a>
                <?php endif; ?>
                <?php if ($this->permissions['delete']) : ?>
                    <a class="confirm"
                       href="<?= $this->url('spareSeller', ['action' => 'delete', 'id' => $line->getId()]); ?>">
                        <img src='/images/del.png' alt='Удалить'>
                    </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
