<h1>Справочник подразделений</h1>

<a href="<?= $this->url('department', ['action' => 'add'])?>" class="btn btn-default">Добавить</a>

<table class="table table-striped table-bordered main-table">
    <thead>
        <tr>
            <th>Наименование</th>
            <th>Вид лома</th>
            <th>Источник металла</th>
            <th>Отображать в списке</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($rows as $line) :?>
            <tr style="<?= $line->isClosed() ? 'color: #ccc;' : ''?>">
                <td><?= $line->getName(); ?></td>
                <td>
                    <?php if ($line->getType() == 'black') : ?>
                        Черный
                    <?php elseif ($line->getType() == 'color') : ?>
                        Цветной
                    <?php endif; ?>
                </td>
                <td>
                    <?php if ($line->getSource()) :?>
                        <?= $line->getSource()->getName(); ?>
                    <?php else :?>
                        Нет
                    <?php endif;?>
                </td>
                <td>
                    <?php if (! $line->isHide()) :?>
                        Да
                    <?php else :?>
                        Нет
                    <?php endif;?>
                </td>
                <td class="action">
                    <a href="<?= $this->url('department', ['action' => 'edit', 'id' => $line->getId()])?>">
                        <img src='/images/edit.png' alt='Редактировать'>
                    </a>
                    <a class="confirm" href="<?= $this->url('department', ['action' => 'delete', 'id' => $line->getId()])?>">
                        <img src='/images/del.png' alt='Удалить'>
                    </a>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
