<?php if ($message) : ?>
    <p class="alert"><?= $message; ?></p>
<?php endif; ?>

<?php
$form = $this->form;
$action = $this->url($this->params['route'], [
    'action' => $this->currentRoute()->getAction(),
    'department' => $this->params['currentDepartmentId'],
    'id' => $id ?? null
]);

$dopElements = [];
?>

<form action="<?= $action; ?>" class="form-horizontal form-add" method="post">
    <div class="col-sm-7">
        <?php foreach ($form as $element) : ?>
            <?php
            if ($element->getAttribute('dopElement')) {
                $dopElements[] = $element;
                continue;
            }
            ?>

            <div class="form-group <?= $this->formElementErrors($element) ? 'error' : '' ?>">
                <label class="col-sm-6 control-label"><?= $element->getLabel(); ?></label>
                <div class="col-sm-6">
                    <?= $this->formElement($element); ?>
                    <?php if ($this->formElementErrors($element)) : ?>
                        <span class="help-inline"><?= $this->formElementErrors($element); ?></span>
                    <?php endif; ?>
                </div>
            </div>

        <?php endforeach; ?>
    </div>

    <div class="col-sm-5">
        <?php foreach ($dopElements as $element) : ?>
            <div class="form-group <?= $this->formElementErrors($element) ? 'error' : '' ?>">
                <label class="col-sm-6 control-label"><?= $element->getLabel(); ?></label>
                <div class="col-sm-6">
                    <?= $this->formElement($element); ?>
                    <?php if ($this->formElementErrors($element)) : ?>
                        <span class="help-inline"><?= $this->formElementErrors($element); ?></span>
                    <?php endif; ?>
                </div>
            </div>

        <?php endforeach; ?>
    </div>


</form>

<div style="clear: both;"></div>
<script>
    $(document).ready(function () {
        $('#dateStart').datepicker();
        $('#dateEnd').datepicker();

        DateNow = $.datepicker.formatDate('yy-mm-dd', new Date()) + ' ';

        $('#specialEquipmentTime').datetimepicker({
            format: 'LT',
            locale: 'ru',
            date: (DateNow + specialEquipmentTime.value),
        });

        $('#engineTime').datetimepicker({
            format: 'LT',
            locale: 'ru',
            date: (DateNow + engineTime.value),
        });
    });

</script>
