<h1>Настройки</h1>


<table class="table table-striped table-bordered main-table">
    <thead>
        <tr>
            <th>Название</th>
            <th>Алиас</th>
            <th>Значение</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($rows as $line) :?>
            <tr>
                <td><?= $line->getLabel(); ?></td>
                <td><?= $line->getAlias(); ?></td>
                <td><?= $line->getValue(); ?></td>
                <td class="action">
                    <a href="<?= $this->url('settings', ['action' => 'edit', 'id' => $line->getId()])?>">
                        <img src='/images/edit.png' alt='Редактировать'>
                    </a>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
