<h1>Справочник банков</h1>

<a href="<?= $this->url('bank', ['action' => 'add'])?>" class="btn btn-default">Добавить</a>

<table class="table table-striped table-bordered main-table">
    <thead>
        <tr>
            <th>Счет</th>
            <th>Банк</th>
            <th>Наличный</th>
            <th>По умолчанию</th>
            <th>Закрыт</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($rows as $line) :?>
            <tr style="<?= $line->getClosed() ? 'color: #ccc;' : ''?>" >
                <td><?= $line->getName(); ?></td>
                <td><?= $line->getBank(); ?></td>
                <td class="col-md-2 text-center">
                    <span class="glyphicon <?= $line->getCash() ? 'glyphicon-ok text-success' : 'glyphicon-remove text-danger'?>" aria-hidden="true"></span>
                </td>
                <td class="col-md-2 text-center">
                    <span class="glyphicon <?= $line->getDef() ? 'glyphicon-ok text-success' : 'glyphicon-remove text-danger'?>" aria-hidden="true"></span>
                </td>
                <td class="col-md-2 text-center">
                    <span class="glyphicon <?= $line->getClosed() ? 'glyphicon-ok text-success' : 'glyphicon-remove text-danger'?>" aria-hidden="true"></span>
                </td>
                <td class="action">
                    <a href="<?= $this->url('bank', ['action' => 'edit','id' => $line->getId()])?>"><img src='/images/edit.png' alt='Редактировать'></a>
                    <a class="confirm" href="<?= $this->url('bank', ['action' => 'delete','id' => $line->getId()])?>"><img src='/images/del.png' alt='Удалить'></a>
                </td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
